project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "README.md"
    - "!attic/**"

markdown:
  extensions: [emoji]

website:
  title: "Deep Learning with mlr3 & torch"
  page-footer:
    center: "CC BY SA 4.0"
  navbar:
    right:
      - icon: "github"
        href: "https://github.com/mlr-org/mlr3torch-course"
    left:
      - text: "General"
        menu:
        - text: "Setup"
          href: "notebooks/setup-guide.html"
        - text: "Resources"
          href: "notebooks/resources.html"
      - text: "Tutorials"
        menu:
          - text: "1. Tensors"
            href: "notebooks/1-tensor.html"
          - text: "2. Autograd"
            href: "notebooks/2-autograd.html"
          - text: "3. Modules and Data"
            href: "notebooks/3-modules-data.html"
          - text: "4. Optimization & Regularization"
            href: "notebooks/4-optimizer.html"
          - text: "5. CNNs"
            href: "notebooks/5-cnn.html"
          - text: "6. mlr3torch"
            href: "notebooks/6-mlr3torch.html"
          - text: "7. Training Efficiency"
            href: "notebooks/7-training-efficiency.html"
      - text: "Exercises"
        menu:
          - text: "Intro"
            href: "notebooks/0-exercise-intro.html"
          - text: "---"
          - text: "1. Tensors"
            href: "notebooks/1-tensor-exercise-task.html"
          - text: "2. Autograd"
            href: "notebooks/2-autograd-exercise-task.html"
          - text: "3. Modules and Data"
            href: "notebooks/3-modules-data-exercise-task.html"
          - text: "4. Optimization & Regularization"
            href: "notebooks/4-optimizer-exercise-task.html"
          - text: "5. CNNs"
            href: "notebooks/5-cnn-exercise-task.html"
          - text: "6. mlr3torch"
            href: "notebooks/6-mlr3torch-exercise-task.html"
          - text: "7. Training Efficiency"
            href: "notebooks/7-training-efficiency-exercise-task.html"
      - text: "Solutions"
        menu:
          - text: "1. Tensors"
            href: "notebooks/1-tensor-exercise-solution.html"
          - text: "2. Autograd"
            href: "notebooks/2-autograd-exercise-solution.html"
          - text: "3. Modules and Data"
            href: "notebooks/3-modules-data-exercise-solution.html"
          - text: "4. Optimization & Regularization"
            href: "notebooks/4-optimizer-exercise-solution.html"
          - text: "5. CNNs"
            href: "notebooks/5-cnn-exercise-solution.html"
          - text: "6. mlr3torch"
            href: "notebooks/6-mlr3torch-exercise-solution.html"
          - text: "7. Training Efficiency"
            href: "notebooks/7-training-efficiency-exercise-solution.html"
